version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    env:
      GODEBUG: madvdontneed=1
    cmds:
      - go build -ldflags="-s -w" -o cmd/server/main cmd/server/main.go
  dev:
    cmds:
      - air
  "migrate:create":
    cmds:
      - migrate create -ext sql -dir migration {{.CLI_ARGS}}
  "migrate:up":
    cmds:
      - migrate -database ${MIGRATE_DB} -path migration up {{.CLI_ARGS}}
  "migrate:down":
    cmds:
      - migrate -database ${MIGRATE_DB} -path migration down {{.CLI_ARGS}}
